CREATE TABLE OpnCVStats 
( Msg_id VARCHAR(20), 
Pgm_Name VARCHAR(100), 
Camera_Name VARCHAR(50), 
Model_Name VARCHAR(100), 
Item_Id VARCHAR(20), 
Item_Desc VARCHAR(100), 
Item_Confidence VARCHAR(10), 
Item_LeftWdw VARCHAR(10), 
Item_TopWdw VARCHAR(10), 
Item_RightWdw VARCHAR(10), 
Item_BottmWdw VARCHAR(10), 
Item_WidthWdw VARCHAR(10), 
Item_HeightWdw VARCHAR(10), 
Item_AreaWdw VARCHAR(10), 
Item_Center VARCHAR(50), 
CrtTS DATETIME, 
rectime VARCHAR(10) , 
jclock VARCHAR(10) , 
jnvmodel VARCHAR(10) , 
jcpu1 VARCHAR(10) , 
jcpu2 VARCHAR(10) , 
jcpu3 VARCHAR(10) , 
jcpu4 VARCHAR(10) , 
jgpu VARCHAR(10) , 
jtempao VARCHAR(10) , 
jtempcpu VARCHAR(10) , 
jtempgpu VARCHAR(10) , 
jtemppll VARCHAR(10) , 
jtempiwlwifi VARCHAR(10) , 
jtempthermal VARCHAR(10) , 
jpowercur VARCHAR(10) )
